# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- '*'

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  webRepository: 'web'
  dockerfilePath: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  #vmImageName: 'ubuntu-20.04'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'MyAgentPool'
    variables:
      - group: Release
    steps:

    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
        dockerVersion: 17.09.0-ce
        releaseType: stable

    - script: sudo /home/azureuser/azcreatecontainer.sh $(dockerfilePath) $(RegistryShortName) $(webRepository) $(tag) $(Build.Repository.LocalPath)
      displayName: 'Build an Docker image'

    - script: sudo /home/azureuser/azcontainerlogin.sh $(RegistryShortName) $(RegistryPass)
      displayName: 'Login to Azure Container Registry'
    
    - script: sudo /home/azureuser/azpushcontainer.sh $(RegistryShortName) $(webRepository) $(tag)
      displayName: 'Push Docker image to Azure Container Registry'
    
    - script: sudo docker logout
      displayName: 'Logout from Azure Container Registry'

- stage: Deploy
  displayName: Deploy the container
  dependsOn: Build
  jobs:
    - job: Deploy
      displayName: Deploy job
      pool:
        name: 'MyAgentPool'
      variables:
        - group: Release
      steps:
        - task: AzureWebAppContainer@1
          inputs:
            appName: $(WebAppName)
            azureSubscription: Resource Manager - Tailspin - Space Game
            imageName: '$(RegistryName)/$(webRepository):$(build.buildId)'
            